### ISSUE TITLE
time data '2021-05-11T00:20:31Z' does not match format '%m/%d/%y'

### ISSUE THREAD

**Issue by GbStudio** [mcauley-penney/OSL-metrics-aggregator#1]
Used the OSL Repo Extractor to extract the OSL Repo Extractor github
[output.json](https://github.com/mcauley-penney/OSL-metrics-aggregator/files/14215639/output.json)

And i get the error when running the aggregator_driver:

python .\aggregator_driver.py .\audacity_metrics_cfg.json

    Partitioning issues into temporal periods...
Traceback (most recent call last):
  File "D:\aaron\Documents\Code\OSL-metrics-aggregator\aggregator_driver.py", line 77, in <module>
    main()
  File "D:\aaron\Documents\Code\OSL-metrics-aggregator\aggregator_driver.py", line 38, in main
    "per_period": improved_period.gather_all_period_comm_metrics(issue_data),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aaron\Documents\Code\OSL-metrics-aggregator\metrics_aggregator\improved\per_period.py", line 39, in gather_all_period_comm_metrics
    issue_buckets: dict = create_partitioned_issue_dict(issue_data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aaron\Documents\Code\OSL-metrics-aggregator\metrics_aggregator\improved\per_period.py", line 110, in create_partitioned_issue_dict
    issue_interval_data = init_issue_interval_dict_keys(issue_data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aaron\Documents\Code\OSL-metrics-aggregator\metrics_aggregator\improved\per_period.py", line 100, in init_issue_interval_dict_keys
    start_date: datetime = get_start_date(issues)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\aaron\Documents\Code\OSL-metrics-aggregator\metrics_aggregator\improved\per_period.py", line 92, in get_start_date
    return datetime.strptime(start_date, "%m/%d/%y")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python311\Lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python311\Lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-05-11T00:20:31Z' does not match format '%m/%d/%y'

**Comment by JonathanRivas457** [comment]
I fixed the formatting issue by parsing the inputted json file and reformatting the dates.

**Comment by mcauley-penney** [comment]
@GbStudio I took some time to actually sit down and sort this out. At some point, I changed the time format the extractor uses for time strings retrieved from the GitHub API, but never adjusted the time formats used for processing those time strings in the aggregator. 

I've updated the aggregator. Please clone it again and give it a try.

**Comment by mcauley-penney** [comment]
@GbStudio I've pushed the file that I have. Find it [here](https://github.com/mcauley-penney/OSL-data/blob/main/extractor/audacity/filtered/audacity_2021-10_filtered.json).
